### ISSUE TITLE
Move Sozi hosting to HTTPS hosting

### ISSUE THREAD

**Issue by aureq** [senshu/Sozi-website#19]
Hi Sozi team,

### Summary of your problem or feature request

Which checking your website today, I noticed it is hosted/served over HTTP rather than HTTPS.
I tried to check the site using `https://sozi.baierouge.fr` but the SSL certificate name doesn't match the URL.

### Steps to reproduce the problem

Go to `http://sozi.baierouge.fr`, the entire site is served over HTTP, not HTTPS.
Go to `https://sozi.baierouge.fr` and your browser will display a warning.

### Expected behavior

Users visiting `sozi.baierouge.fr` should be able to securely access the site over HTTPS. Users accessing `http://sozi.baierouge.fr` should be redirected to `https://sozi.baierouge.fr` automatically.

### Hints and solutions (optional)

1. SSL Certificate. `Let's Encrypt` provides free, valid and trusted SSL certificates that are valid for 90 days. Since certificatre issuance is entirely API driven, there's a lot of Let's Encrypt clients: https://letsencrypt.org/docs/client-options/ I personally use `GetSSL` and it works very well.
To check the installation, you may want to use something like SSL Labs: https://www.ssllabs.com/ssltest/analyze.html?d=sozi.baierouge.fr&hideResults=on

2. For Apache (`2.4.25`) it's possible to create a smart redirect to match each HTTP url to its HTTPS counter part. Some example here: https://www.tecmint.com/redirect-http-to-https-on-apache/

Side note: In addition to increase security and privacy, HTTPS is often faster. Details here: https://www.httpvshttps.com/

Thanks a lot for considering this issue.

**Comment by senshu** [comment]
Yes. This is something I have always wanted to do, but I kept on delaying the operation. Thanks for the reminder.
I have followed your proposal and the site is now available over HTTPS with an automatic redirection from HTTP.

Please tell me if you find something strange.

**Comment by aureq** [comment]
Hi @senshu 

Thanks a lot for your quick action. This is much appreciated. I've done a few checks and here is some feedback.

The _smart_ HTTP to HTTPS redirect is partly broken. For example, going to `http://sozi.baierouge.fr/foo` will redirect the user to `https://sozi.baierouge.frfoo`. Si there's a missing `/`

On the SSL/TLS part, the configuration is a bit weak and I don't know if this is intentional. I usually use Mozilla's web server configuration generator. As you run Apache 2.4.25, here is an example for a more modern web config (it's a generated example that you may want to adapt): https://mozilla.github.io/server-side-tls/ssl-config-generator/?server=apache-2.4.25&openssl=1.0.1e&hsts=yes&profile=modern

Hope this helps.

Cheers

**Comment by senshu** [comment]
> it's a generated example that you may want to adapt

OK. Thanks for your help.

I have copied the configuration from the Mozilla generator and I now get an A+ rating from SSL Labs.
I'm afraid my understanding of the topic is too limited. I don't have a clear idea about what settings would be worth adapting.

I assume that removing the weak cipher suites would improve the score for "Cipher strength" but what would be the consequences?

**Comment by aureq** [comment]
The consequences are loosing some compatibility (not all) on older browsers, like Internet Explorer and other outdated browsers. So all in all, that should have a minimal impact with the visitors anyway.

**Comment by aureq** [comment]
Closing the issue as everything looks fine to me. Thanks a lot @senshu
